[Hotfix] - Store Detected Contour
ichiro-its/ninshiki_cpp pull request #10
Opened 2024-02-15 10:44 UTC by FaaizHaikal

## Jira Link: 

## Description
Add method to store the detected contour

## Type of Change

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause the existing functionality to not work as expected)

## How Has This Been Tested?

- [ ] New unit tests added.
- [x] Manual tested.

## Checklist:

- [x] Using Branch Name Convention
    - `feature/JIRA-ID-SHORT-DESCRIPTION` if has a JIRA ticket
    - `enhancement/SHORT-DESCRIPTION` if has/has no JIRA ticket and contain enhancement
    - `hotfix/SHORT-DESCRIPTION` if the change doesn't need to be tested (urgent)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made the documentation for the corresponding changes.

2024-02-15 10:48 UTC, JayantiTA approved these changes

2024-02-19 02:00 UTC, threeal requested changes
Anyway, since there are both `set_countours` and `add_countour` functions, i think it's better to just expose the `countours` variable instead.

2024-02-19 02:00 UTC, threeal commented on include/ninshiki_cpp/utils/contours.hpp
> +  void add_contour(std::vector<cv::Point> contour);
```suggestion
  void add_contour(const std::vector<cv::Point>& contour);
```

2024-02-19 14:54 UTC, FaaizHaikal commented on include/ninshiki_cpp/utils/contours.hpp
> +  void add_contour(std::vector<cv::Point> contour);
You mean make it public, mas?

2024-02-20 03:00 UTC, threeal commented on include/ninshiki_cpp/utils/contours.hpp
> +  void add_contour(std::vector<cv::Point> contour);
yes

2024-02-20 08:17 UTC, threeal commented on include/ninshiki_cpp/utils/contours.hpp
> -  void add_contour(std::vector<cv::Point> contour);
The `get_contours` function is unnecessary since the `contours` variable is already public.

2024-02-20 13:07 UTC, threeal approved these changes

2024-02-21 07:59 UTC, threeal requested changes

2024-02-21 07:59 UTC, threeal commented on data/color_classifier.json
> +}
missing EoL

2024-02-21 07:59 UTC, threeal commented on src/ninshiki_cpp/detector/color_detector.cpp
> +        name,
Straightforward:
```suggestion
        item.key(),
```

2024-02-21 11:56 UTC, threeal approved these changes

2024-03-04 10:38 UTC, merged